loongarch: Fix Shenandoah SATB barrier runtime entry point
Upstream 8356289 renamed ShenandoahRuntime::write_ref_field_pre(oopDesc*,
JavaThread*) to write_barrier_pre(oopDesc*), dropping the thread
argument, and updated aarch64/riscv/ppc/x86 accordingly. The loongarch
port kept calling the removed symbol, which broke the build:

  shenandoahBarrierSetAssembler_loongarch.cpp:175:72: error:
  'write_ref_field_pre' is not a member of 'ShenandoahRuntime'

Follow the other ports: call ShenandoahRuntime::write_barrier_pre with
the pre-value only.

Signed-off-by: lsyes <3294271542@qq.com>